export const majorFormFields = [
  { name: "title", label: "Title", placeholder: "Computer Science" },
  { name: "description", label: "Description", type: "textarea", placeholder: "Detailed description of the major" },
  { name: "featured", label: "Featured Major", type: "checkbox", description: "Show this major in featured sections" },
  { name: "learning_objectives", label: "Learning Objectives", type: "array", placeholder: "Problem solving, Critical thinking" },
  { name: "common_courses", label: "Common Courses", type: "array", placeholder: "Calculus, Data Structures" },
  { name: "interdisciplinary_connections", label: "Interdisciplinary Connections", type: "array", placeholder: "Mathematics, Physics" },
  { name: "job_prospects", label: "Job Prospects", type: "textarea", placeholder: "Description of career opportunities and job market" },
  { name: "certifications_to_consider", label: "Recommended Certifications", type: "array", placeholder: "AWS Certified, Google Cloud" },
  { name: "degree_levels", label: "Degree Levels", type: "array", placeholder: "Bachelor's, Master's" },
  { name: "affiliated_programs", label: "Affiliated Programs", type: "array", placeholder: "Research programs, Industry partnerships" },
  { name: "gpa_expectations", label: "GPA Expectations", type: "number", placeholder: "3.0" },
  { name: "transferable_skills", label: "Transferable Skills", type: "array", placeholder: "Communication, Leadership" },
  { name: "tools_knowledge", label: "Tools and Technologies", type: "array", placeholder: "Python, Java" },
  { name: "potential_salary", label: "Potential Salary Range", placeholder: "$60,000 - $120,000" },
  { name: "passion_for_subject", label: "Passion for Subject", placeholder: "High interest in technology and problem-solving" },
  { name: "skill_match", label: "Required Skills", type: "array", placeholder: "Mathematics, Logic" },
  { name: "professional_associations", label: "Professional Associations", type: "array", placeholder: "IEEE, ACM" },
  { name: "global_applicability", label: "Global Applicability", type: "textarea", placeholder: "Description of worldwide career opportunities" },
  { name: "common_difficulties", label: "Common Difficulties", type: "array", placeholder: "Complex mathematics, Time management" },
  { name: "career_opportunities", label: "Career Opportunities", type: "array", placeholder: "Software Engineer, Data Scientist" },
  { name: "intensity", label: "Program Intensity", placeholder: "High, Medium, or Low" },
  { name: "stress_level", label: "Stress Level", placeholder: "High, Medium, or Low" },
  { name: "dropout_rates", label: "Dropout Rates", placeholder: "e.g., 15%" },
  { name: "majors_to_consider_switching_to", label: "Alternative Majors", type: "array", placeholder: "Information Technology, Data Science" }
];