
[functions.manage-session]
verify_jwt = true

[functions.reschedule_session]
verify_jwt = true

[functions.cancel_session]
verify_jwt = true

[functions.send-session-reminder]
verify_jwt = true

[functions.send-session-email]
verify_jwt = false

[functions.check-scheduled-reminders]
verify_jwt = false
