
project_id = "wurdmlkfkzuivvwxjmxk"
[config]
# Replace the following with your DeepSeek API key or set as environment variable
DEEPSEEK_API_KEY = ""

# Configuring the AI to generate more structured and concise responses
RESPONSE_FORMAT = "structured_json"
QUESTION_MAX_LENGTH = 60
OPTIONS_MAX_COUNT = 4
OPTIONS_MAX_LENGTH = 30
CATEGORIES = ["education", "skills", "workstyle", "goals"]
QUESTION_MIN_COUNT_PER_CATEGORY = 3
CATEGORY_TRACKING = "enabled"
