
project_id = "wurdmlkfkzuivvwxjmxk"
[config]
# DeepSeek API key is set via environment variables
DEEPSEEK_API_KEY = ""

# Response format configuration
AI_RESPONSE_FORMAT = "structured"
STRUCTURED_RESPONSE_VERSION = "3"
QUESTION_MAX_LENGTH = 60
OPTIONS_MAX_COUNT = 8
OPTIONS_MAX_LENGTH = 40
CATEGORY_TRACKING = "enabled"

# Structured format instruction
# This will instruct the AI to return responses in the specified format
STRUCTURED_FORMAT_INSTRUCTION = """
Return responses in one of these JSON formats:

For questions during the assessment:
{
  "type": "question",
  "content": {
    "intro": "Optional friendly intro text",
    "question": "The actual question being asked",
    "options": [
      {
        "id": "unique-id",
        "text": "Option text",
        "icon": "optional-icon-name",
        "description": "Optional description"
      }
    ]
  },
  "metadata": {
    "progress": {
      "category": "education|skills|workstyle|goals",
      "current": 1,
      "total": 6,
      "overall": 25
    },
    "options": {
      "type": "single",
      "layout": "cards|chips|buttons"
    }
  }
}

For final recommendations at the end of the assessment:
{
  "type": "recommendation",
  "sections": {
    "introduction": {
      "title": "Your Career Assessment Results",
      "summary": "A brief summary of the assessment results",
      "completionDate": "Current date string",
      "overallInsight": "Overall insight about the user's profile"
    },
    "careers": [
      {
        "title": "Career title",
        "match": 85,
        "description": "What makes this career a good match",
        "keySkills": ["Skill 1", "Skill 2", "Skill 3"],
        "education": "Typical education requirements"
      }
    ],
    "personalityInsights": [
      {
        "trait": "Trait name",
        "strength": 90,
        "description": "Description of this personality trait"
      }
    ],
    "growthAreas": [
      {
        "skill": "Skill to develop",
        "priority": "high|medium|low",
        "description": "Why this skill is important",
        "resources": ["Resource 1", "Resource 2"]
      }
    ],
    "closing": {
      "message": "Thank you for completing your career assessment!",
      "nextSteps": [
        "Explore these career paths in detail",
        "Connect with mentors in these fields",
        "Develop the suggested skills"
      ]
    }
  },
  "metadata": {
    "type": "final_recommendation",
    "isComplete": true
  }
}

For a session end message:
{
  "type": "session_end",
  "content": {
    "message": "Thank you for completing your career assessment! This session is now complete.",
    "suggestions": [
      "Start a new career assessment",
      "Explore these career paths in detail",
      "Save these recommendations"
    ]
  },
  "metadata": {
    "isSessionEnd": true,
    "completionType": "career_recommendations"
  }
}
"""

