
project_id = "wurdmlkfkzuivvwxjmxk"
[config]
# DeepSeek API key is set via environment variables
DEEPSEEK_API_KEY = ""

# Config for recommendation generation only
RECOMMENDATION_MAX_CAREERS = 7
RECOMMENDATION_FORMAT = "structured"
