export interface Major {
  id: string;
  title: string;
  description: string;
  image_url: string | null;
  created_at: string;
  updated_at: string;
  featured: boolean | null;
  field_of_study: string | null;
  required_courses: string[] | null;
  degree_level: string | null;
  career_opportunities: string[] | null;
  learning_objectives: string[] | null;
  common_courses: string[] | null;
  interdisciplinary_connections: string[] | null;
  job_prospects: string | null;
  certifications_to_consider: string[] | null;
  degree_levels: string[] | null;
  affiliated_programs: string[] | null;
  gpa_expectations: number | null;
  transferable_skills: string[] | null;
  tools_knowledge: string[] | null;
  tuition_and_fees: number | null;
  potential_salary: number | null;
  intensity: number | null;
  passion_for_subject: string | null;
  skill_match: string[] | null;
  professional_associations: string[] | null;
  global_applicability: string | null;
  common_difficulties: string[] | null;
  stress_levels: number | null;
  dropout_rates: number | null;
  majors_to_consider_switching_to: string[] | null;
}