export interface Profile {
  id: string;
  first_name: string | null;
  last_name: string | null;
  full_name: string | null;
  email: string | null;
  avatar_url: string | null;
  position: string | null;
  highest_degree: string | null;
  academic_major_id: string | null;
  school_id: string | null;
  company_id: string | null;
  career_id: string | null;
  skills: string[] | null;
  tools_used: string[] | null;
  keywords: string[] | null;
  bio: string | null;
  linkedin_url: string | null;
  github_url: string | null;
  website_url: string | null;
  years_of_experience: number | null;
  location: string | null;
  fields_of_interest: string[] | null;
  user_type: string | null;
  top_mentor: boolean | null;
  created_at: string | null;
  updated_at: string | null;
  // Include joined fields
  company_name?: string | null;
  school_name?: string | null;
  academic_major?: string | null;
}