// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmvxzxbrtnmdtnkhejwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdnh6eGJydG5tZHRua2hlandlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2NzI1NjMsImV4cCI6MjA1MDI0ODU2M30.uCq3-z7kkL9y2MwkkzgucDc2eJ5JJrXSOABaFdofLa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);