
export const subcategories: string[] = [
  "AI and Machine Learning",
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Cybersecurity",
  "Software Engineering",
  "Academic Research",
  "Clinical Experience",
  "Laboratory Work",
  "Fieldwork",
  "Internships",
  "Study Groups",
  "Student Organizations",
  "Leadership Roles",
  "Community Outreach",
  "Volunteer Work",
  "Social Impact",
  "Environmental Initiatives",
  "Startup Experience",
  "Business Development",
  "Product Management",
  "Marketing",
  "Finance",
  "Investment",
  "Personal Finance",
  "Budgeting",
  "Scholarships",
  "Grants",
  "Financial Aid",
  "Visual Arts",
  "Performing Arts",
  "Creative Writing",
  "Design",
  "Music",
  "Theater",
  "Film",
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Engineering",
  "Computer Science",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Literature",
  "History",
  "Philosophy",
  "Languages",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Political Science"
];
